level_map = [
"XXXXXXXXXXXXXXX ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"        P       ",
"                ",
]