
level_map = [
    "1bbbbbbbKKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1   A   KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1   G   KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1 P     KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1       KKKKKKKKKKKKKKKKKKKKKKK",
    "1bbbbbbbKKKKKKKKKKKKKKKKKKKKKKK"
]
level_settings = [len(level_map[0]) , len(level_map )]
level_offset_x = 0
level_offset_y = 0
horizontal_changes = [1]
vertical_changes = []