
level_map = [
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "  P    KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK",
    "       KKKKKKKKKKKKKKKKKKKKKKK"
]
level_settings = [len(level_map[0]) , len(level_map )]
level_offset_x = 0
level_offset_y = 0
horizontal_changes = [1]
vertical_changes = []