level_map = [
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKb",
"K         K         K                      Kb",
"K       C K         K                      Kb",
"K         K         K                      Kb",
"K   KKKKKKKKKKKKK   KKKKK   K   KKKKKKKK   Kb",
"K   K           K       K   K   K          Kb",
"K   K           K       K   K   K C        Kb",
"K   K           K       K   K   K          Kb",
"K   KKKKKKKKK   KKKKK   KKKKK   KKKKKKKKKKKKb",
"K                   K                       1",
"K                   K                  P    1",
"K                   K                       1",
"K   KKKKKKKKK   K   KKKKKKKKK   KKKKKKKKKKKKb",
"K   K       K               K   KKKK       Kb",
"K   K       K               K   KKKK       Kb",
"K   K       K               K   KKKK       Kb",
"K   K   K   KKKKKKKKK   K   K   KKKK   K   Kb",
"K   K   K           K   K   K   KKKK   K   Kb",
"K   K   K           K   K       KKKK   K   Kb",
"K   K   K           K   K       KKKK   K   Kb",
"K   K   K   K       K   K       KKKK   K   Kb",
"K   K   K   K       KKKKKKKKK   KKKK   K   Kb",
"K   K   K   K       K                  K   Kb",
"K   K   K   K   M   K                  K C Kb",
"K   K   K   K       K                  K   Kb",
"K   K   K   KKKKKKKKK   KKKKK   KKKKKKKKKKKKb",
"K       K      K        K   K              Kb",
"K       K    C K        K   K              Kb",
"K       K      K        K   K              Kb",
"KKKKKKKKKKKKKKKK    KKKKK   K   KKKKKKKK   Kb",
"K                               KKKKKKKK   Kb",
"K                               KKKKKKKK   Kb",
"K                               KKKKKKKK   Kb",
"K   KKKKKKKKKKKK   KKKKKKKKKKKKKKKKKKKKK   Kb",
"K   K          K   KKKKKKKKKKKKKKKKKKKKK   Kb",
"K   K        C K   KKKKKKKKKKKKK       K   Kb",
"K   K          K   K           K       K   Kb",
"K   K   KKKKKKKK   K           K       K   Kb",
"K   K              K           K   KKKKK   Kb",
"K   K              K   KKKKK   K   K   K   Kb",
"K   K              K       K   K   K   K   Kb",
"K   KKKKKKKKKKKKKKKK       K   K   K   K   Kb",
"K   KKKKKKKKKKKKKKKK       K   K   K   K   Kb",
"K   KKKKKKKKKKKKKKKK   KKKKK   K   K       Kb",
"K                  K       K   K   K       Kb",
"K                  K       K   K   K       Kb",
"K                  K       K   K   K   KKKKKb",
"KKKKKKKKKK   KKKKKKK   KKKKK   K   K       Kb",
"K        K   K         K           K       Kb",
"K        K   K         K           K       Kb",
"K        K   K         K           K       Kb",
"K  M     K   KKKKKKK   K   K   KKKKKKKKK   Kb",
"K        K             K       K   K       Kb",
"K        K             K       K   K       Kb",
"K        K             K       K   K       Kb",
"KKKKKK   KKKKKKKKKKKKKKKKKKKKKKK   K    KKKKb",
"KKKKKK              K              K       Kb",
"KKKKKK              K              K       Kb",
"KKKKKK              K              K       Kb",
"KKKKKK   KKKKKKKK   K   KKKKKKKK   KKKKK   Kb",
"KKKKKK   KKKKKKKK   K   KKKKKKKK   KKKKK   Kb",
"K               K              K           Kb",
"K Ç             K              K           Kb",
"K               K              K           Kb",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKb",]
level_settings = [len(level_map[0]) , len(level_map )]
level_offset_x = 32
level_offset_y = 4
horizontal_changes = [1]
vertical_changes = []