level_map = [
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXb",
"X         X         X                      Xb",
"X       C X         X                      Xb",
"X         X         X                      Xb",
"X   XXXXXXXXXXXXX   XXXXX   X   XXXXXXXX   Xb",
"X   X           X       X   X   X          Xb",
"X   X           X       X   X   X C        Xb",
"X   X           X       X   X   X          Xb",
"X   XXXXXXXXX   XXXXX   XXXXX   XXXXXXXXXXXXb",
"X                   X                       1",
"X                   X                  P    1",
"X                   X                       1",
"X   XXXXXXXXX   X   XXXXXXXXX   XXXXXXXXXXXXb",
"X   X       X               X   XXXX       Xb",
"X   X       X               X   XXXX       Xb",
"X   X       X               X   XXXX       Xb",
"X   X   X   XXXXXXXXX   X   X   XXXX   X   Xb",
"X   X   X           X   X   X   XXXX   X   Xb",
"X   X   X           X   X       XXXX   X   Xb",
"X   X   X           X   X       XXXX   X   Xb",
"X   X   X   X       X   X       XXXX   X   Xb",
"X   X   X   X       XXXXXXXXX   XXXX   X   Xb",
"X   X   X   X       X                  X   Xb",
"X   X   X   X   M   X                  X C Xb",
"X   X   X   X       X                  X   Xb",
"X   X   X   XXXXXXXXX   XXXXX   XXXXXXXXXXXXb",
"X       X      X        X   X              Xb",
"X       X    C X        X   X              Xb",
"X       X      X        X   X              Xb",
"XXXXXXXXXXXXXXXX    XXXXX   X   XXXXXXXX   Xb",
"X                               XXXXXXXX   Xb",
"X                               XXXXXXXX   Xb",
"X                               XXXXXXXX   Xb",
"X   XXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXX   Xb",
"X   X          X   XXXXXXXXXXXXXXXXXXXXX   Xb",
"X   X        C X   XXXXXXXXXXXXX       X   Xb",
"X   X          X   X           X       X   Xb",
"X   X   XXXXXXXX   X           X       X   Xb",
"X   X              X           X   XXXXX   Xb",
"X   X              X   XXXXX   X   X   X   Xb",
"X   X              X       X   X   X   X   Xb",
"X   XXXXXXXXXXXXXXXX       X   X   X   X   Xb",
"X   XXXXXXXXXXXXXXXX       X   X   X   X   Xb",
"X   XXXXXXXXXXXXXXXX   XXXXX   X   X       Xb",
"X                  X       X   X   X       Xb",
"X                  X       X   X   X       Xb",
"X                  X       X   X   X   XXXXXb",
"XXXXXXXXXX   XXXXXXX   XXXXX   X   X       Xb",
"X        X   X         X           X       Xb",
"X        X   X         X           X       Xb",
"X        X   X         X           X       Xb",
"X  M     X   XXXXXXX   X   X   XXXXXXXXX   Xb",
"X        X             X       X   X       Xb",
"X        X             X       X   X       Xb",
"X        X             X       X   X       Xb",
"XXXXXX   XXXXXXXXXXXXXXXXXXXXXXX   X    XXXXb",
"XXXXXX              X              X       Xb",
"XXXXXX              X              X       Xb",
"XXXXXX              X              X       Xb",
"XXXXXX   XXXXXXXX   X   XXXXXXXX   XXXXX   Xb",
"XXXXXX   XXXXXXXX   X   XXXXXXXX   XXXXX   Xb",
"X               X              X           Xb",
"X Ç             X              X           Xb",
"X               X              X           Xb",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXb",]
level_settings = [len(level_map[0]) , len(level_map )]
level_offset_x = 35
level_offset_y = 4
horizontal_changes = [1]
vertical_changes = []